export const demoJobs = [
  {
    id: "1",
    title: "Frontend Developer (React)",
    company: "Spotify",
    description: "Work on user-facing features using React and TypeScript. Collaborate with designers and backend engineers to build scalable web applications.",
    country: "Sweden",
    location: "Remote",
    url: "https://www.spotifyjobs.com",
    source: "LinkedIn",
    level: "Mid",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-10",
  },
  {
    id: "2",
    title: "React Developer",
    company: "Revolut",
    description: "Build high-performance financial dashboards. Improve UX and optimize frontend performance across the platform.",
    country: "United Kingdom",
    location: "London",
    url: "https://www.revolut.com/careers",
    source: "Company Website",
    level: "Mid-Senior",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-10",
  },
  {
    id: "3",
    title: "Full Stack Developer",
    company: "Notion",
    description: "Develop full-stack features using modern JavaScript frameworks. Work closely with product teams to deliver new tools.",
    country: "USA",
    location: "Remote",
    url: "https://www.notion.so/careers",
    source: "LinkedIn",
    level: "Senior",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-10",
  },
  {
    id: "4",
    title: "JavaScript Engineer",
    company: "Amazon",
    description: "Create scalable web applications and internal tools. Focus on performance and reliability in a high-load environment.",
    country: "Italy",
    location: "Milan",
    url: "https://www.amazon.jobs",
    source: "Indeed",
    level: "Mid",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-10",
  },
  {
    id: "5",
    title: "Frontend Engineer",
    company: "Bolt",
    description: "Develop and maintain UI components for mobility services. Ensure fast and responsive user interfaces.",
    country: "Estonia",
    location: "Remote",
    url: "https://careers.bolt.eu",
    source: "LinkedIn",
    level: "Junior-Mid",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-10",
  },
  {
    id: "6",
    title: "UI Developer",
    company: "Shopify",
    description: "Build polished and accessible UI for e-commerce tools. Work with design systems and reusable components.",
    country: "Canada",
    location: "Remote",
    url: "https://www.shopify.com/careers",
    source: "Company Website",
    level: "Mid",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-10",
  },
  {
    id: "7",
    title: "Frontend Developer",
    company: "Airbnb",
    description: "Create seamless booking experiences. Work with React, GraphQL, and modern frontend tooling.",
    country: "USA",
    location: "Remote",
    url: "https://careers.airbnb.com",
    source: "LinkedIn",
    level: "Mid-Senior",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-10",
  },
  {
    id: "8",
    title: "Web Developer",
    company: "Zalando",
    description: "Develop scalable frontend solutions for a large e-commerce platform. Focus on performance and accessibility.",
    country: "Germany",
    location: "Berlin",
    url: "https://jobs.zalando.com",
    source: "Indeed",
    level: "Junior",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-10",
  },
];